<?xml version="1.0" encoding="utf-8"?>
<body xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <LD>
  <comment localId="257" height="4" width="20">
   <position x="225" y="140" />
   <content>
    <html xmlns="http://www.w3.org/1999/xhtml">
     <head xmlns="">
      <title />
     </head>
     <body xmlns="">
      <p style="font-family:Arial;font-weight:normal;font-style:normal;font-size:11.00pt;">Connect to database</p>
     </body>
    </html>
   </content>
   <addData>
    <data name="commentInformation" handleUnknown="preserve">
     <commentInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoSize="true" parentMainId="292" parentSubId="-1" parentBaseType="Object" executionOrderId="0" isJumpLabel="false" />
    </data>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="7" subNetworkId="0" />
    </data>
   </addData>
  </comment>
  <comment localId="258" height="4" width="30">
   <position x="30" y="116" />
   <content>
    <html xmlns="http://www.w3.org/1999/xhtml">
     <head xmlns="">
      <title />
     </head>
     <body xmlns="">
      <p style="font-family:Arial;font-weight:normal;font-style:normal;font-size:11.00pt;">Insert data into the table Example</p>
     </body>
    </html>
   </content>
   <addData>
    <data name="commentInformation" handleUnknown="preserve">
     <commentInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoSize="true" parentMainId="1" parentSubId="-1" parentBaseType="Object" executionOrderId="0" isJumpLabel="false" />
    </data>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="10" subNetworkId="0" />
    </data>
   </addData>
  </comment>
  <comment localId="259" height="4" width="30">
   <position x="155" y="4" />
   <content>
    <html xmlns="http://www.w3.org/1999/xhtml">
     <head xmlns="">
      <title />
     </head>
     <body xmlns="">
      <p style="font-family:Arial;font-weight:normal;font-style:normal;font-size:11.00pt;">Read data from the table Example</p>
     </body>
    </html>
   </content>
   <addData>
    <data name="commentInformation" handleUnknown="preserve">
     <commentInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoSize="true" parentMainId="152" parentSubId="-1" parentBaseType="Object" executionOrderId="0" isJumpLabel="false" />
    </data>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="11" subNetworkId="0" />
    </data>
   </addData>
  </comment>
  <comment localId="260" height="4" width="25">
   <position x="70" y="4" />
   <content>
    <html xmlns="http://www.w3.org/1999/xhtml">
     <head xmlns="">
      <title />
     </head>
     <body xmlns="">
      <p style="font-family:Arial;font-weight:normal;font-style:normal;font-size:11.00pt;">Create the table Example</p>
     </body>
    </html>
   </content>
   <addData>
    <data name="commentInformation" handleUnknown="preserve">
     <commentInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoSize="true" parentMainId="108" parentSubId="-1" parentBaseType="Object" executionOrderId="0" isJumpLabel="false" />
    </data>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="12" subNetworkId="0" />
    </data>
   </addData>
  </comment>
  <comment localId="261" height="4" width="30">
   <position x="325" y="144" />
   <content>
    <html xmlns="http://www.w3.org/1999/xhtml">
     <head xmlns="">
      <title />
     </head>
     <body xmlns="">
      <p style="font-family:Arial;font-weight:normal;font-style:normal;font-size:11.00pt;">Decode the data from the database</p>
     </body>
    </html>
   </content>
   <addData>
    <data name="commentInformation" handleUnknown="preserve">
     <commentInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoSize="true" parentMainId="308" parentSubId="-1" parentBaseType="Object" executionOrderId="0" isJumpLabel="false" />
    </data>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="13" subNetworkId="0" />
    </data>
   </addData>
  </comment>
  <comment localId="262" height="4" width="35">
   <position x="255" y="236" />
   <content>
    <html xmlns="http://www.w3.org/1999/xhtml">
     <head xmlns="">
      <title />
     </head>
     <body xmlns="">
      <p style="font-family:Arial;font-weight:normal;font-style:normal;font-size:11.00pt;">Send commands to the database (FiFo)</p>
     </body>
    </html>
   </content>
   <addData>
    <data name="commentInformation" handleUnknown="preserve">
     <commentInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoSize="true" parentMainId="195" parentSubId="-1" parentBaseType="Object" executionOrderId="0" isJumpLabel="false" />
    </data>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="14" subNetworkId="0" />
    </data>
   </addData>
  </comment>
  <comment localId="263" height="4" width="30">
   <position x="175" y="240" />
   <content>
    <html xmlns="http://www.w3.org/1999/xhtml">
     <head xmlns="">
      <title />
     </head>
     <body xmlns="">
      <p style="font-family:Arial;font-weight:normal;font-style:normal;font-size:11.00pt;">Insert data into the table Example2</p>
     </body>
    </html>
   </content>
   <addData>
    <data name="commentInformation" handleUnknown="preserve">
     <commentInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoSize="true" parentMainId="221" parentSubId="-1" parentBaseType="Object" executionOrderId="0" isJumpLabel="false" />
    </data>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="15" subNetworkId="0" />
    </data>
   </addData>
  </comment>
  <inVariable localId="6" height="4" width="13" executionOrderId="1">
   <position x="16" y="128" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="29" height="4" width="13" executionOrderId="1">
   <position x="201" y="152" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xIP_Activate</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="106" height="4" width="13" executionOrderId="1">
   <position x="151" y="152" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xReadyCom</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="2" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="130" height="4" width="18" executionOrderId="1">
   <position x="51" y="12" />
   <connectionPointOut>
    <relPosition x="18" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer.Data</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="175" height="4" width="18" executionOrderId="1">
   <position x="146" y="12" />
   <connectionPointOut>
    <relPosition x="18" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer.Data</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="6" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="185" height="4" width="13" executionOrderId="1">
   <position x="286" y="156" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xReadyCode2</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="194" height="4" width="8" executionOrderId="1">
   <position x="181" y="132" />
   <connectionPointOut>
    <relPosition x="8" y="2" />
   </connectionPointOut>
   <expression>INT#0</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="8" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="245" height="4" width="18" executionOrderId="1">
   <position x="161" y="252" />
   <connectionPointOut>
    <relPosition x="18" y="2" />
   </connectionPointOut>
   <expression>udtComBufferIn.Data</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="18" height="4" width="13" executionOrderId="2">
   <position x="86" y="128" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="30" height="4" width="13" executionOrderId="2">
   <position x="201" y="156" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xDB_Activate</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="104" height="4" width="18" executionOrderId="2">
   <position x="196" y="132" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="194">
     <position x="196" y="134" />
     <position x="189" y="134" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer.Mode</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="8" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="133" height="4" width="13" executionOrderId="2">
   <position x="151" y="156" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xReadyCode</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="2" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="177" height="4" width="13" executionOrderId="2">
   <position x="151" y="16" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xActivateCode2</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="6" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="178" height="4" width="13" executionOrderId="2">
   <position x="56" y="16" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xActivateCode</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="184" height="4" width="13" executionOrderId="2">
   <position x="286" y="160" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xSQLDone</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="205" height="4" width="13" executionOrderId="2">
   <position x="236" y="252" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>udtComBufferIn</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="10" height="4" width="13" executionOrderId="3">
   <position x="16" y="132" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xActivateCom</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="31" height="4" width="13" executionOrderId="3">
   <position x="201" y="160" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>strDB_User</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="179" width="8" height="12" typeName="AND" executionOrderId="3">
   <position x="301" y="152" />
   <inputVariables>
    <variable formalParameter="IN1" hidden="true">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="185">
       <position x="301" y="158" />
       <position x="299" y="158" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN2" hidden="true">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="184">
       <position x="301" y="162" />
       <position x="299" y="162" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables />
   <outputVariables>
    <variable formalParameter="AND" hidden="true">
     <connectionPointOut>
      <relPosition x="8" y="6" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="false" extensible="true" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="IN1" localId="180" executionOrderId="3" negatable="true" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="AND" localId="182" executionOrderId="3" negatable="true" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="IN2" localId="181" executionOrderId="3" negatable="true" editorParameter="false" priority="4" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <inVariable localId="206" height="4" width="23" executionOrderId="3">
   <position x="46" y="20" />
   <connectionPointOut>
    <relPosition x="23" y="2" />
   </connectionPointOut>
   <expression>'CREATE TABLE Example ('</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="212" height="4" width="23" executionOrderId="3">
   <position x="141" y="20" />
   <connectionPointOut>
    <relPosition x="23" y="2" />
   </connectionPointOut>
   <expression>'SELECT * FROM Example;'</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="6" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="218" height="4" width="13" executionOrderId="3">
   <position x="151" y="160" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xReadyCode2</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="2" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="247" height="4" width="18" executionOrderId="3">
   <position x="161" y="256" />
   <connectionPointOut>
    <relPosition x="18" y="2" />
   </connectionPointOut>
   <expression>xActivateCodeFifo</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="11" height="4" width="13" executionOrderId="4">
   <position x="16" y="136" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>strStartCom</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="32" height="4" width="13" executionOrderId="4">
   <position x="201" y="164" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>strDB_Password</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="152" width="18" height="84" typeName="DBFL_CODE_1" instanceName="DBFL_CODE_1_2" executionOrderId="4">
   <position x="166" y="8" />
   <inputVariables>
    <variable formalParameter="ACTIVATE">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="177">
       <position x="166" y="18" />
       <position x="164" y="18" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_1">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="212">
       <position x="166" y="22" />
       <position x="164" y="22" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_2">
     <connectionPointIn>
      <relPosition x="0" y="18" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_3">
     <connectionPointIn>
      <relPosition x="0" y="22" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_4">
     <connectionPointIn>
      <relPosition x="0" y="26" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_5">
     <connectionPointIn>
      <relPosition x="0" y="30" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_6">
     <connectionPointIn>
      <relPosition x="0" y="34" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_7">
     <connectionPointIn>
      <relPosition x="0" y="38" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_8">
     <connectionPointIn>
      <relPosition x="0" y="42" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_9">
     <connectionPointIn>
      <relPosition x="0" y="46" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_10">
     <connectionPointIn>
      <relPosition x="0" y="50" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_11">
     <connectionPointIn>
      <relPosition x="0" y="54" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_12">
     <connectionPointIn>
      <relPosition x="0" y="58" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_13">
     <connectionPointIn>
      <relPosition x="0" y="62" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_14">
     <connectionPointIn>
      <relPosition x="0" y="66" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_15">
     <connectionPointIn>
      <relPosition x="0" y="70" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_16">
     <connectionPointIn>
      <relPosition x="0" y="74" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_17">
     <connectionPointIn>
      <relPosition x="0" y="78" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_18">
     <connectionPointIn>
      <relPosition x="0" y="82" />
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="SQL_OUT">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="175">
       <position x="166" y="14" />
       <position x="164" y="14" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="18" y="6" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="READY">
     <connectionPointOut>
      <relPosition x="18" y="10" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="6" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="SQL_OUT" localId="173" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="ACTIVATE" localId="153" executionOrderId="4" negatable="true" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="READY" localId="172" executionOrderId="4" negatable="true" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_1" localId="154" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_2" localId="155" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_3" localId="156" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_4" localId="157" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_5" localId="158" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_6" localId="159" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_7" localId="160" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_8" localId="161" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_9" localId="162" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_10" localId="163" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_11" localId="164" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_12" localId="165" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_13" localId="166" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_14" localId="167" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_15" localId="168" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_16" localId="169" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_17" localId="170" executionOrderId="4" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_18" localId="171" executionOrderId="4" editorParameter="false" priority="4" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <inVariable localId="190" height="4" width="13" executionOrderId="4">
   <position x="316" y="160" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>iRowSelect</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="204" height="4" width="13" executionOrderId="4">
   <position x="236" y="256" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="207" height="4" width="13" executionOrderId="4">
   <position x="56" y="24" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>'Column1 int, '</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="250" height="4" width="13" executionOrderId="4">
   <position x="151" y="164" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xNewData</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="2" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="1" width="28" height="16" typeName="DBFL_StartComT2_1" instanceName="DBFL_StartComT2_1_1" executionOrderId="5">
   <position x="31" y="124" />
   <inputVariables>
    <variable formalParameter="IN_xActivate">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="10">
       <position x="31" y="134" />
       <position x="29" y="134" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_strStartString">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="11">
       <position x="31" y="138" />
       <position x="29" y="138" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="INOUT_udtComBuffer">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="6">
       <position x="31" y="130" />
       <position x="29" y="130" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="28" y="6" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="OUT_DataValid">
     <connectionPointOut>
      <relPosition x="28" y="10" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="INOUT_udtComBuffer" localId="5" executionOrderId="5" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="IN_xActivate" localId="2" executionOrderId="5" negatable="true" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="OUT_DataValid" localId="4" executionOrderId="5" negatable="true" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="IN_strStartString" localId="3" executionOrderId="5" editorParameter="false" priority="4" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <inVariable localId="33" height="4" width="13" executionOrderId="5">
   <position x="201" y="168" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>strIP_Address</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="176" height="4" width="18" executionOrderId="5">
   <position x="186" y="12" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="152" formalParameter="SQL_OUT">
     <position x="186" y="14" />
     <position x="184" y="14" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer.Data</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="6" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="191" height="4" width="13" executionOrderId="5">
   <position x="316" y="164" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>iColSelect</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="208" height="4" width="13" executionOrderId="5">
   <position x="56" y="28" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>'Column2 real, '</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="248" height="4" width="33" executionOrderId="5">
   <position x="146" y="260" />
   <connectionPointOut>
    <relPosition x="33" y="2" />
   </connectionPointOut>
   <expression>'INSERT INTO Example2 VALUES (10,20)'</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="256" width="8" height="20" typeName="OR" executionOrderId="5">
   <position x="166" y="148" />
   <inputVariables>
    <variable formalParameter="IN1" hidden="true">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="106">
       <position x="166" y="154" />
       <position x="164" y="154" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN2" hidden="true">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="133">
       <position x="166" y="158" />
       <position x="164" y="158" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN3" hidden="true">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="218">
       <position x="166" y="162" />
       <position x="164" y="162" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN4" hidden="true">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="250">
       <position x="166" y="166" />
       <position x="164" y="166" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables />
   <outputVariables>
    <variable formalParameter="OR" hidden="true">
     <connectionPointOut>
      <relPosition x="8" y="6" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="2" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="false" extensible="true" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="IN1" localId="251" executionOrderId="5" negatable="true" editorParameter="false" priority="5" />
      <parameterInformation formalParameter="OR" localId="254" executionOrderId="5" negatable="true" editorParameter="false" priority="5" />
      <parameterInformation formalParameter="IN2" localId="252" executionOrderId="5" negatable="true" editorParameter="false" priority="5" />
      <parameterInformation formalParameter="IN3" localId="253" executionOrderId="5" negatable="true" editorParameter="false" priority="5" />
      <parameterInformation formalParameter="IN4" localId="255" executionOrderId="5" negatable="true" editorParameter="false" priority="5" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <outVariable localId="7" height="4" width="13" executionOrderId="6">
   <position x="66" y="128" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="1" formalParameter="INOUT_udtComBuffer">
     <position x="66" y="130" />
     <position x="59" y="130" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="34" height="4" width="13" executionOrderId="6">
   <position x="201" y="172" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>strIP_Port</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="107" height="4" width="13" executionOrderId="6">
   <position x="176" y="152" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="256" formalParameter="OR">
     <position x="176" y="154" />
     <position x="174" y="154" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>xDB_Activate</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="2" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="174" height="4" width="13" executionOrderId="6">
   <position x="186" y="16" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="152" formalParameter="READY">
     <position x="186" y="18" />
     <position x="184" y="18" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>xReadyCode2</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="6" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="188" height="4" width="13" executionOrderId="6">
   <position x="316" y="168" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>diRowCNT</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="209" height="4" width="18" executionOrderId="6">
   <position x="51" y="32" />
   <connectionPointOut>
    <relPosition x="18" y="2" />
   </connectionPointOut>
   <expression>'Column3 tinyint, '</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="221" width="18" height="84" typeName="DBFL_CODE_1" instanceName="DBFL_CODE_1_3" executionOrderId="6">
   <position x="181" y="248" />
   <inputVariables>
    <variable formalParameter="ACTIVATE">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="247">
       <position x="181" y="258" />
       <position x="179" y="258" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_1">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="248">
       <position x="181" y="262" />
       <position x="179" y="262" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_2">
     <connectionPointIn>
      <relPosition x="0" y="18" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_3">
     <connectionPointIn>
      <relPosition x="0" y="22" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_4">
     <connectionPointIn>
      <relPosition x="0" y="26" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_5">
     <connectionPointIn>
      <relPosition x="0" y="30" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_6">
     <connectionPointIn>
      <relPosition x="0" y="34" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_7">
     <connectionPointIn>
      <relPosition x="0" y="38" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_8">
     <connectionPointIn>
      <relPosition x="0" y="42" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_9">
     <connectionPointIn>
      <relPosition x="0" y="46" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_10">
     <connectionPointIn>
      <relPosition x="0" y="50" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_11">
     <connectionPointIn>
      <relPosition x="0" y="54" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_12">
     <connectionPointIn>
      <relPosition x="0" y="58" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_13">
     <connectionPointIn>
      <relPosition x="0" y="62" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_14">
     <connectionPointIn>
      <relPosition x="0" y="66" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_15">
     <connectionPointIn>
      <relPosition x="0" y="70" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_16">
     <connectionPointIn>
      <relPosition x="0" y="74" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_17">
     <connectionPointIn>
      <relPosition x="0" y="78" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_18">
     <connectionPointIn>
      <relPosition x="0" y="82" />
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="SQL_OUT">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="245">
       <position x="181" y="254" />
       <position x="179" y="254" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="18" y="6" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="READY">
     <connectionPointOut>
      <relPosition x="18" y="10" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="SQL_OUT" localId="242" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="ACTIVATE" localId="222" executionOrderId="6" negatable="true" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="READY" localId="241" executionOrderId="6" negatable="true" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_1" localId="223" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_2" localId="224" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_3" localId="225" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_4" localId="226" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_5" localId="227" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_6" localId="228" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_7" localId="229" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_8" localId="230" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_9" localId="231" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_10" localId="232" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_11" localId="233" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_12" localId="234" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_13" localId="235" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_14" localId="236" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_15" localId="237" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_16" localId="238" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_17" localId="239" executionOrderId="6" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="STR_18" localId="240" executionOrderId="6" editorParameter="false" priority="4" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <inVariable localId="20" height="4" width="8" executionOrderId="7">
   <position x="91" y="136" />
   <connectionPointOut>
    <relPosition x="8" y="2" />
   </connectionPointOut>
   <expression>iIntCom</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="35" height="4" width="13" executionOrderId="7">
   <position x="201" y="176" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>strDB_Name</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="189" height="4" width="13" executionOrderId="7">
   <position x="316" y="172" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>diColCNT</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="210" height="4" width="13" executionOrderId="7">
   <position x="56" y="36" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>'Column4 bit, '</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="244" height="4" width="18" executionOrderId="7">
   <position x="201" y="252" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="221" formalParameter="SQL_OUT">
     <position x="201" y="254" />
     <position x="199" y="254" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBufferIn.Data</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="16" height="4" width="13" executionOrderId="8">
   <position x="201" y="184" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>strHost_Name</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="61" height="4" width="13" executionOrderId="8">
   <position x="86" y="140" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>BYTE#44</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="150" height="4" width="13" executionOrderId="8">
   <position x="316" y="192" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>arrRcvBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="211" height="4" width="18" executionOrderId="8">
   <position x="51" y="40" />
   <connectionPointOut>
    <relPosition x="18" y="2" />
   </connectionPointOut>
   <expression>'Column5 datetime);'</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="243" height="4" width="8" executionOrderId="8">
   <position x="241" y="260" />
   <connectionPointOut>
    <relPosition x="8" y="2" />
   </connectionPointOut>
   <expression>xSend</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="12" height="4" width="18" executionOrderId="9">
   <position x="196" y="196" />
   <connectionPointOut>
    <relPosition x="18" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer.Data</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="21" width="23" height="20" typeName="DBFL_IntToComT2_1" instanceName="DBFL_IntToComT2_1_1" executionOrderId="9">
   <position x="101" y="124" />
   <inputVariables>
    <variable formalParameter="IN_xActivate">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="1" formalParameter="OUT_DataValid">
       <position x="101" y="134" />
       <position x="59" y="134" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_iValue">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="20">
       <position x="101" y="138" />
       <position x="99" y="138" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_bLastChar">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="61">
       <position x="101" y="142" />
       <position x="99" y="142" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="INOUT_udtComBuffer">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="18">
       <position x="101" y="130" />
       <position x="99" y="130" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="23" y="6" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="OUT_DataValid">
     <connectionPointOut>
      <relPosition x="23" y="10" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="INOUT_udtComBuffer" localId="60" executionOrderId="9" editorParameter="false" priority="8" />
      <parameterInformation formalParameter="IN_xActivate" localId="22" executionOrderId="9" negatable="true" editorParameter="false" priority="8" />
      <parameterInformation formalParameter="OUT_DataValid" localId="59" executionOrderId="9" negatable="true" editorParameter="false" priority="8" />
      <parameterInformation formalParameter="IN_iValue" localId="23" executionOrderId="9" editorParameter="false" priority="8" />
      <parameterInformation formalParameter="IN_bLastChar" localId="24" executionOrderId="9" negatable="true" editorParameter="false" priority="8" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <block localId="108" width="18" height="84" typeName="DBFL_CODE_1" instanceName="DBFL_CODE_1_1" executionOrderId="9">
   <position x="71" y="8" />
   <inputVariables>
    <variable formalParameter="ACTIVATE">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="178">
       <position x="71" y="18" />
       <position x="69" y="18" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_1">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="206">
       <position x="71" y="22" />
       <position x="69" y="22" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_2">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="207">
       <position x="71" y="26" />
       <position x="69" y="26" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_3">
     <connectionPointIn>
      <relPosition x="0" y="22" />
      <connection refLocalId="208">
       <position x="71" y="30" />
       <position x="69" y="30" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_4">
     <connectionPointIn>
      <relPosition x="0" y="26" />
      <connection refLocalId="209">
       <position x="71" y="34" />
       <position x="69" y="34" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_5">
     <connectionPointIn>
      <relPosition x="0" y="30" />
      <connection refLocalId="210">
       <position x="71" y="38" />
       <position x="69" y="38" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_6">
     <connectionPointIn>
      <relPosition x="0" y="34" />
      <connection refLocalId="211">
       <position x="71" y="42" />
       <position x="69" y="42" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_7">
     <connectionPointIn>
      <relPosition x="0" y="38" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_8">
     <connectionPointIn>
      <relPosition x="0" y="42" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_9">
     <connectionPointIn>
      <relPosition x="0" y="46" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_10">
     <connectionPointIn>
      <relPosition x="0" y="50" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_11">
     <connectionPointIn>
      <relPosition x="0" y="54" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_12">
     <connectionPointIn>
      <relPosition x="0" y="58" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_13">
     <connectionPointIn>
      <relPosition x="0" y="62" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_14">
     <connectionPointIn>
      <relPosition x="0" y="66" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_15">
     <connectionPointIn>
      <relPosition x="0" y="70" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_16">
     <connectionPointIn>
      <relPosition x="0" y="74" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_17">
     <connectionPointIn>
      <relPosition x="0" y="78" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="STR_18">
     <connectionPointIn>
      <relPosition x="0" y="82" />
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="SQL_OUT">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="130">
       <position x="71" y="14" />
       <position x="69" y="14" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="18" y="6" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="READY">
     <connectionPointOut>
      <relPosition x="18" y="10" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="SQL_OUT" localId="129" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="ACTIVATE" localId="109" executionOrderId="9" negatable="true" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="READY" localId="128" executionOrderId="9" negatable="true" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_1" localId="110" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_2" localId="111" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_3" localId="112" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_4" localId="113" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_5" localId="114" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_6" localId="115" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_7" localId="116" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_8" localId="117" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_9" localId="118" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_10" localId="119" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_11" localId="120" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_12" localId="121" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_13" localId="122" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_14" localId="123" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_15" localId="124" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_16" localId="125" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_17" localId="126" executionOrderId="9" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STR_18" localId="127" executionOrderId="9" editorParameter="false" priority="9" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <inVariable localId="246" height="4" width="8" executionOrderId="9">
   <position x="241" y="268" />
   <connectionPointOut>
    <relPosition x="8" y="2" />
   </connectionPointOut>
   <expression>Time#5s</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="308" width="23" height="44" typeName="DBFL_TSQL_DECODE_2" instanceName="DBFL_TSQL_DECODE_1_2" executionOrderId="9">
   <position x="331" y="152" />
   <inputVariables>
    <variable formalParameter="ACTIVATE">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="179" formalParameter="AND">
       <position x="331" y="158" />
       <position x="309" y="158" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="ROW_SELECT">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="190">
       <position x="331" y="162" />
       <position x="329" y="162" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="COL_SELECT">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="191">
       <position x="331" y="166" />
       <position x="329" y="166" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="MAX_ROW">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="188">
       <position x="331" y="170" />
       <position x="329" y="170" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="MAX_COL">
     <connectionPointIn>
      <relPosition x="0" y="22" />
      <connection refLocalId="189">
       <position x="331" y="174" />
       <position x="329" y="174" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="RCV_BUFFER">
     <connectionPointIn>
      <relPosition x="0" y="42" />
      <connection refLocalId="150">
       <position x="331" y="194" />
       <position x="329" y="194" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="23" y="42" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="READY">
     <connectionPointOut>
      <relPosition x="23" y="6" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="NEW_DATA">
     <connectionPointOut>
      <relPosition x="23" y="10" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="DONE">
     <connectionPointOut>
      <relPosition x="23" y="14" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="ERROR">
     <connectionPointOut>
      <relPosition x="23" y="18" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="STATUS">
     <connectionPointOut>
      <relPosition x="23" y="22" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="DATA_TYPE">
     <connectionPointOut>
      <relPosition x="23" y="26" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="DINT_OUT">
     <connectionPointOut>
      <relPosition x="23" y="30" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="REAL_OUT">
     <connectionPointOut>
      <relPosition x="23" y="34" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="STR_OUT">
     <connectionPointOut>
      <relPosition x="23" y="38" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="ACTIVATE" localId="293" executionOrderId="9" negatable="true" editorParameter="false" priority="1" />
      <parameterInformation formalParameter="ROW_SELECT" localId="294" executionOrderId="9" editorParameter="false" priority="2" />
      <parameterInformation formalParameter="COL_SELECT" localId="295" executionOrderId="9" editorParameter="false" priority="3" />
      <parameterInformation formalParameter="MAX_ROW" localId="296" executionOrderId="9" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="MAX_COL" localId="297" executionOrderId="9" editorParameter="false" priority="5" />
      <parameterInformation formalParameter="READY" localId="298" executionOrderId="9" negatable="true" editorParameter="false" priority="6" />
      <parameterInformation formalParameter="NEW_DATA" localId="299" executionOrderId="9" negatable="true" editorParameter="false" priority="7" />
      <parameterInformation formalParameter="DONE" localId="300" executionOrderId="9" negatable="true" editorParameter="false" priority="8" />
      <parameterInformation formalParameter="ERROR" localId="301" executionOrderId="9" negatable="true" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="STATUS" localId="302" executionOrderId="9" editorParameter="false" priority="10" />
      <parameterInformation formalParameter="DATA_TYPE" localId="303" executionOrderId="9" editorParameter="false" priority="11" />
      <parameterInformation formalParameter="DINT_OUT" localId="304" executionOrderId="9" editorParameter="false" priority="12" />
      <parameterInformation formalParameter="REAL_OUT" localId="305" executionOrderId="9" editorParameter="false" priority="13" />
      <parameterInformation formalParameter="STR_OUT" localId="306" executionOrderId="9" editorParameter="false" priority="14" />
      <parameterInformation formalParameter="RCV_BUFFER" localId="307" executionOrderId="9" editorParameter="false" priority="15" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <inVariable localId="14" height="4" width="13" executionOrderId="10">
   <position x="201" y="200" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>arrRcvBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="19" height="4" width="13" executionOrderId="10">
   <position x="126" y="128" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="21" formalParameter="INOUT_udtComBuffer">
     <position x="126" y="130" />
     <position x="124" y="130" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="131" height="4" width="18" executionOrderId="10">
   <position x="91" y="12" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="108" formalParameter="SQL_OUT">
     <position x="91" y="14" />
     <position x="89" y="14" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer.Data</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="151" height="4" width="13" executionOrderId="10">
   <position x="361" y="192" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="308" formalParameter="RCV_BUFFER">
     <position x="361" y="194" />
     <position x="354" y="194" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>arrRcvBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="4" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <block localId="195" width="33" height="24" typeName="DBFL_CommandFiFo_1" instanceName="DBFL_CommandFiFo_1_1" executionOrderId="10">
   <position x="251" y="248" />
   <inputVariables>
    <variable formalParameter="IN_xEnableSend">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="243">
       <position x="251" y="262" />
       <position x="249" y="262" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_xNewData">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="221" formalParameter="READY">
       <position x="251" y="266" />
       <position x="225" y="266" />
       <position x="225" y="258" />
       <position x="199" y="258" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_tCycleTime">
     <connectionPointIn>
      <relPosition x="0" y="22" />
      <connection refLocalId="246">
       <position x="251" y="270" />
       <position x="249" y="270" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="INOUT_udtComBufferIn">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="205">
       <position x="251" y="254" />
       <position x="249" y="254" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="33" y="6" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="INOUT_udtComBufferOut">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="204">
       <position x="251" y="258" />
       <position x="249" y="258" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="33" y="10" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="OUT_xNewData">
     <connectionPointOut>
      <relPosition x="33" y="14" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="OUT_iCommandCounter">
     <connectionPointOut>
      <relPosition x="33" y="18" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="OUT_xOverflow">
     <connectionPointOut>
      <relPosition x="33" y="22" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="INOUT_udtComBufferIn" localId="202" executionOrderId="10" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="INOUT_udtComBufferOut" localId="203" executionOrderId="10" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="IN_xEnableSend" localId="196" executionOrderId="10" negatable="true" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="OUT_xNewData" localId="199" executionOrderId="10" negatable="true" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="IN_xNewData" localId="197" executionOrderId="10" negatable="true" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="OUT_iCommandCounter" localId="200" executionOrderId="10" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="IN_tCycleTime" localId="198" executionOrderId="10" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="OUT_xOverflow" localId="201" executionOrderId="10" negatable="true" editorParameter="false" priority="9" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <inVariable localId="69" height="4" width="13" executionOrderId="11">
   <position x="16" y="160" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="132" height="4" width="13" executionOrderId="11">
   <position x="91" y="16" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="108" formalParameter="READY">
     <position x="91" y="18" />
     <position x="89" y="18" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>xReadyCode</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="3" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="219" height="4" width="13" executionOrderId="11">
   <position x="286" y="252" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="195" formalParameter="INOUT_udtComBufferIn">
     <position x="286" y="254" />
     <position x="284" y="254" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBufferIn</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <block localId="292" width="33" height="56" typeName="DBFL_TSQL_ACCESS_2" instanceName="DBFL_TSQL_ACCESS_1_2" executionOrderId="11">
   <position x="216" y="148" />
   <inputVariables>
    <variable formalParameter="IP_ACTIVATE">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="29">
       <position x="216" y="154" />
       <position x="214" y="154" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="DB_ACTIVATE">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="30">
       <position x="216" y="158" />
       <position x="214" y="158" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="DB_USER">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="31">
       <position x="216" y="162" />
       <position x="214" y="162" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="DB_PASSWORD">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="32">
       <position x="216" y="166" />
       <position x="214" y="166" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IP_ADDRESS">
     <connectionPointIn>
      <relPosition x="0" y="22" />
      <connection refLocalId="33">
       <position x="216" y="170" />
       <position x="214" y="170" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IP_PORT">
     <connectionPointIn>
      <relPosition x="0" y="26" />
      <connection refLocalId="34">
       <position x="216" y="174" />
       <position x="214" y="174" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="DB_NAME">
     <connectionPointIn>
      <relPosition x="0" y="30" />
      <connection refLocalId="35">
       <position x="216" y="178" />
       <position x="214" y="178" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="TIME_OUT">
     <connectionPointIn>
      <relPosition x="0" y="34" />
     </connectionPointIn>
    </variable>
    <variable formalParameter="HOST_NAME">
     <connectionPointIn>
      <relPosition x="0" y="38" />
      <connection refLocalId="16">
       <position x="216" y="186" />
       <position x="214" y="186" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="SQL_IN">
     <connectionPointIn>
      <relPosition x="0" y="50" />
      <connection refLocalId="12">
       <position x="216" y="198" />
       <position x="214" y="198" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="33" y="50" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="RCV_BUFFER">
     <connectionPointIn>
      <relPosition x="0" y="54" />
      <connection refLocalId="14">
       <position x="216" y="202" />
       <position x="214" y="202" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="33" y="54" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="TCP_READY">
     <connectionPointOut>
      <relPosition x="33" y="6" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="SQL_READY">
     <connectionPointOut>
      <relPosition x="33" y="10" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="SQL_DONE">
     <connectionPointOut>
      <relPosition x="33" y="14" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="SQL_SERVER_INFO">
     <connectionPointOut>
      <relPosition x="33" y="18" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="ERROR">
     <connectionPointOut>
      <relPosition x="33" y="22" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="TCP_STATUS">
     <connectionPointOut>
      <relPosition x="33" y="26" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="SQL_STATUS">
     <connectionPointOut>
      <relPosition x="33" y="30" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="SQL_ERRMSG">
     <connectionPointOut>
      <relPosition x="33" y="34" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="RCV_SIZE">
     <connectionPointOut>
      <relPosition x="33" y="38" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="ROW_CNT">
     <connectionPointOut>
      <relPosition x="33" y="42" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="COL_CNT">
     <connectionPointOut>
      <relPosition x="33" y="46" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="IP_ACTIVATE" localId="270" executionOrderId="11" negatable="true" editorParameter="false" priority="1" />
      <parameterInformation formalParameter="DB_ACTIVATE" localId="271" executionOrderId="11" negatable="true" editorParameter="false" priority="2" />
      <parameterInformation formalParameter="DB_USER" localId="272" executionOrderId="11" editorParameter="false" priority="3" />
      <parameterInformation formalParameter="DB_PASSWORD" localId="273" executionOrderId="11" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="IP_ADDRESS" localId="274" executionOrderId="11" editorParameter="false" priority="5" />
      <parameterInformation formalParameter="IP_PORT" localId="275" executionOrderId="11" editorParameter="false" priority="6" />
      <parameterInformation formalParameter="DB_NAME" localId="276" executionOrderId="11" editorParameter="false" priority="7" />
      <parameterInformation formalParameter="TIME_OUT" localId="277" executionOrderId="11" editorParameter="false" priority="8" />
      <parameterInformation formalParameter="HOST_NAME" localId="278" executionOrderId="11" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="TCP_READY" localId="279" executionOrderId="11" negatable="true" editorParameter="false" priority="10" />
      <parameterInformation formalParameter="SQL_READY" localId="280" executionOrderId="11" negatable="true" editorParameter="false" priority="11" />
      <parameterInformation formalParameter="SQL_DONE" localId="281" executionOrderId="11" negatable="true" editorParameter="false" priority="12" />
      <parameterInformation formalParameter="SQL_SERVER_INFO" localId="282" executionOrderId="11" editorParameter="false" priority="13" />
      <parameterInformation formalParameter="ERROR" localId="283" executionOrderId="11" negatable="true" editorParameter="false" priority="14" />
      <parameterInformation formalParameter="TCP_STATUS" localId="284" executionOrderId="11" editorParameter="false" priority="15" />
      <parameterInformation formalParameter="SQL_STATUS" localId="285" executionOrderId="11" editorParameter="false" priority="16" />
      <parameterInformation formalParameter="SQL_ERRMSG" localId="286" executionOrderId="11" editorParameter="false" priority="17" />
      <parameterInformation formalParameter="RCV_SIZE" localId="287" executionOrderId="11" editorParameter="false" priority="18" />
      <parameterInformation formalParameter="ROW_CNT" localId="288" executionOrderId="11" editorParameter="false" priority="19" />
      <parameterInformation formalParameter="COL_CNT" localId="289" executionOrderId="11" editorParameter="false" priority="20" />
      <parameterInformation formalParameter="SQL_IN" localId="290" executionOrderId="11" editorParameter="false" priority="21" />
      <parameterInformation formalParameter="RCV_BUFFER" localId="291" executionOrderId="11" editorParameter="false" priority="22" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <inVariable localId="78" height="4" width="13" executionOrderId="12">
   <position x="81" y="160" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="192" height="4" width="13" executionOrderId="12">
   <position x="251" y="152" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="292" formalParameter="TCP_READY">
     <position x="251" y="154" />
     <position x="249" y="154" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>xTCP_Ready</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="220" height="4" width="13" executionOrderId="12">
   <position x="286" y="256" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="195" formalParameter="INOUT_udtComBufferOut">
     <position x="286" y="258" />
     <position x="284" y="258" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="70" height="4" width="13" executionOrderId="13">
   <position x="16" y="168" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>rRealCom</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="193" height="4" width="13" executionOrderId="13">
   <position x="251" y="156" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="292" formalParameter="SQL_READY">
     <position x="251" y="158" />
     <position x="249" y="158" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>xSQL_Ready</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="249" height="4" width="13" executionOrderId="13">
   <position x="286" y="260" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="195" formalParameter="OUT_xNewData">
     <position x="286" y="262" />
     <position x="284" y="262" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>xNewData</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="9" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="80" height="4" width="13" executionOrderId="14">
   <position x="81" y="168" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>bByteCom</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="183" height="4" width="13" executionOrderId="14">
   <position x="251" y="160" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="292" formalParameter="SQL_DONE">
     <position x="251" y="162" />
     <position x="249" y="162" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>xSQLDone</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="71" height="4" width="13" executionOrderId="15">
   <position x="16" y="172" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>BYTE#44</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <outVariable localId="186" height="4" width="13" executionOrderId="15">
   <position x="251" y="188" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="292" formalParameter="ROW_CNT">
     <position x="251" y="190" />
     <position x="249" y="190" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>diRowCNT</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <block localId="62" width="23" height="20" typeName="DBFL_RealToComT2_1" instanceName="DBFL_RealToComT2_1_1" executionOrderId="16">
   <position x="31" y="156" />
   <inputVariables>
    <variable formalParameter="IN_xActivate">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="21" formalParameter="OUT_DataValid">
       <position x="31" y="166" />
       <position x="30" y="166" />
       <position x="30" y="155" />
       <position x="125" y="155" />
       <position x="125" y="134" />
       <position x="124" y="134" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_rValue">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="70">
       <position x="31" y="170" />
       <position x="29" y="170" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_bLastChar">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="71">
       <position x="31" y="174" />
       <position x="29" y="174" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="INOUT_udtComBuffer">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="69">
       <position x="31" y="162" />
       <position x="29" y="162" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="23" y="6" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="OUT_DataValid">
     <connectionPointOut>
      <relPosition x="23" y="10" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="INOUT_udtComBuffer" localId="67" executionOrderId="16" editorParameter="false" priority="13" />
      <parameterInformation formalParameter="IN_xActivate" localId="63" executionOrderId="16" negatable="true" editorParameter="false" priority="13" />
      <parameterInformation formalParameter="OUT_DataValid" localId="66" executionOrderId="16" negatable="true" editorParameter="false" priority="13" />
      <parameterInformation formalParameter="IN_rValue" localId="64" executionOrderId="16" editorParameter="false" priority="13" />
      <parameterInformation formalParameter="IN_bLastChar" localId="65" executionOrderId="16" negatable="true" editorParameter="false" priority="13" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <outVariable localId="187" height="4" width="13" executionOrderId="16">
   <position x="251" y="192" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="292" formalParameter="COL_CNT">
     <position x="251" y="194" />
     <position x="249" y="194" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>diColCNT</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="13" height="4" width="18" executionOrderId="17">
   <position x="251" y="196" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="292" formalParameter="SQL_IN">
     <position x="251" y="198" />
     <position x="249" y="198" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer.Data</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="68" height="4" width="13" executionOrderId="17">
   <position x="61" y="160" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="62" formalParameter="INOUT_udtComBuffer">
     <position x="61" y="162" />
     <position x="54" y="162" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="15" height="4" width="13" executionOrderId="18">
   <position x="251" y="200" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="292" formalParameter="RCV_BUFFER">
     <position x="251" y="202" />
     <position x="249" y="202" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>arrRcvBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="1" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="81" height="4" width="13" executionOrderId="18">
   <position x="81" y="172" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>BYTE#44</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="72" width="23" height="20" typeName="DBFL_ByteToComT2_1" instanceName="DBFL_ByteToComT2_1_1" executionOrderId="19">
   <position x="96" y="156" />
   <inputVariables>
    <variable formalParameter="IN_xActivate">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="62" formalParameter="OUT_DataValid">
       <position x="96" y="166" />
       <position x="54" y="166" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_bValue">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="80">
       <position x="96" y="170" />
       <position x="94" y="170" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_bLastChar">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="81">
       <position x="96" y="174" />
       <position x="94" y="174" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="INOUT_udtComBuffer">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="78">
       <position x="96" y="162" />
       <position x="94" y="162" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="23" y="6" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="OUT_DataValid">
     <connectionPointOut>
      <relPosition x="23" y="10" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="INOUT_udtComBuffer" localId="77" executionOrderId="19" editorParameter="false" priority="17" />
      <parameterInformation formalParameter="IN_xActivate" localId="73" executionOrderId="19" negatable="true" editorParameter="false" priority="17" />
      <parameterInformation formalParameter="OUT_DataValid" localId="76" executionOrderId="19" negatable="true" editorParameter="false" priority="17" />
      <parameterInformation formalParameter="IN_bValue" localId="74" executionOrderId="19" negatable="true" editorParameter="false" priority="17" />
      <parameterInformation formalParameter="IN_bLastChar" localId="75" executionOrderId="19" negatable="true" editorParameter="false" priority="17" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <outVariable localId="79" height="4" width="13" executionOrderId="20">
   <position x="126" y="160" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="72" formalParameter="INOUT_udtComBuffer">
     <position x="126" y="162" />
     <position x="119" y="162" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <inVariable localId="88" height="4" width="13" executionOrderId="21">
   <position x="16" y="192" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="91" height="4" width="13" executionOrderId="22">
   <position x="16" y="200" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>xBoolCom</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="90" height="4" width="13" executionOrderId="23">
   <position x="16" y="204" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>BYTE#44</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="82" width="23" height="20" typeName="DBFL_BoolToComT2_1" instanceName="DBFL_BoolToComT2_1_1" executionOrderId="24">
   <position x="31" y="188" />
   <inputVariables>
    <variable formalParameter="IN_xActivate">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="72" formalParameter="OUT_DataValid">
       <position x="31" y="198" />
       <position x="30" y="198" />
       <position x="30" y="177" />
       <position x="120" y="177" />
       <position x="120" y="166" />
       <position x="119" y="166" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_xValue">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="91">
       <position x="31" y="202" />
       <position x="29" y="202" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_bLastChar">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="90">
       <position x="31" y="206" />
       <position x="29" y="206" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="INOUT_udtComBuffer">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="88">
       <position x="31" y="194" />
       <position x="29" y="194" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="23" y="6" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="OUT_DataValid">
     <connectionPointOut>
      <relPosition x="23" y="10" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="INOUT_udtComBuffer" localId="87" executionOrderId="24" editorParameter="false" priority="22" />
      <parameterInformation formalParameter="IN_xActivate" localId="83" executionOrderId="24" negatable="true" editorParameter="false" priority="22" />
      <parameterInformation formalParameter="OUT_DataValid" localId="86" executionOrderId="24" negatable="true" editorParameter="false" priority="22" />
      <parameterInformation formalParameter="IN_xValue" localId="84" executionOrderId="24" negatable="true" editorParameter="false" priority="22" />
      <parameterInformation formalParameter="IN_bLastChar" localId="85" executionOrderId="24" negatable="true" editorParameter="false" priority="22" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <outVariable localId="89" height="4" width="13" executionOrderId="25">
   <position x="56" y="192" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="82" formalParameter="INOUT_udtComBuffer">
     <position x="56" y="194" />
     <position x="54" y="194" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <block localId="51" width="18" height="40" typeName="PBCL_DateTimeGet_1" instanceName="PBCL_DateTimeGet_11" executionOrderId="26">
   <position x="36" y="212" />
   <inputVariables />
   <inOutVariables />
   <outputVariables>
    <variable formalParameter="iYear">
     <connectionPointOut>
      <relPosition x="18" y="6" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="iMonth">
     <connectionPointOut>
      <relPosition x="18" y="10" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="iDay">
     <connectionPointOut>
      <relPosition x="18" y="14" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="iHour">
     <connectionPointOut>
      <relPosition x="18" y="18" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="iMinute">
     <connectionPointOut>
      <relPosition x="18" y="22" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="iSecond">
     <connectionPointOut>
      <relPosition x="18" y="26" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="iMillisecond">
     <connectionPointOut>
      <relPosition x="18" y="30" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="iMicrosecond">
     <connectionPointOut>
      <relPosition x="18" y="34" />
     </connectionPointOut>
    </variable>
    <variable formalParameter="dtDateTime">
     <connectionPointOut>
      <relPosition x="18" y="38" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="iYear" localId="52" executionOrderId="26" editorParameter="false" priority="1" />
      <parameterInformation formalParameter="iMonth" localId="53" executionOrderId="26" editorParameter="false" priority="2" />
      <parameterInformation formalParameter="iDay" localId="54" executionOrderId="26" editorParameter="false" priority="3" />
      <parameterInformation formalParameter="iHour" localId="55" executionOrderId="26" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="iMinute" localId="56" executionOrderId="26" editorParameter="false" priority="5" />
      <parameterInformation formalParameter="iSecond" localId="57" executionOrderId="26" editorParameter="false" priority="6" />
      <parameterInformation formalParameter="iMillisecond" localId="58" executionOrderId="26" editorParameter="false" priority="7" />
      <parameterInformation formalParameter="iMicrosecond" localId="92" executionOrderId="26" editorParameter="false" priority="8" />
      <parameterInformation formalParameter="dtDateTime" localId="93" executionOrderId="26" editorParameter="false" priority="9" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <inVariable localId="103" height="4" width="13" executionOrderId="27">
   <position x="81" y="224" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>BYTE#41</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <inVariable localId="99" height="4" width="13" executionOrderId="28">
   <position x="81" y="228" />
   <connectionPointOut>
    <relPosition x="13" y="2" />
   </connectionPointOut>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </inVariable>
  <block localId="269" width="23" height="40" typeName="DBFL_DateTimeStrT2_2" instanceName="DBFL_DateTimeStrT2_1_2" executionOrderId="29">
   <position x="96" y="192" />
   <inputVariables>
    <variable formalParameter="IN_xActivate">
     <connectionPointIn>
      <relPosition x="0" y="6" />
      <connection refLocalId="82" formalParameter="OUT_DataValid">
       <position x="96" y="198" />
       <position x="54" y="198" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_iYear">
     <connectionPointIn>
      <relPosition x="0" y="10" />
      <connection refLocalId="51" formalParameter="iYear">
       <position x="96" y="202" />
       <position x="75" y="202" />
       <position x="75" y="218" />
       <position x="54" y="218" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_iMonth">
     <connectionPointIn>
      <relPosition x="0" y="14" />
      <connection refLocalId="51" formalParameter="iMonth">
       <position x="96" y="206" />
       <position x="76" y="206" />
       <position x="76" y="222" />
       <position x="54" y="222" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_iDay">
     <connectionPointIn>
      <relPosition x="0" y="18" />
      <connection refLocalId="51" formalParameter="iDay">
       <position x="96" y="210" />
       <position x="77" y="210" />
       <position x="77" y="226" />
       <position x="54" y="226" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_iHour">
     <connectionPointIn>
      <relPosition x="0" y="22" />
      <connection refLocalId="51" formalParameter="iHour">
       <position x="96" y="214" />
       <position x="78" y="214" />
       <position x="78" y="230" />
       <position x="54" y="230" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_iMinute">
     <connectionPointIn>
      <relPosition x="0" y="26" />
      <connection refLocalId="51" formalParameter="iMinute">
       <position x="96" y="218" />
       <position x="79" y="218" />
       <position x="79" y="234" />
       <position x="54" y="234" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_iSecond">
     <connectionPointIn>
      <relPosition x="0" y="30" />
      <connection refLocalId="51" formalParameter="iSecond">
       <position x="96" y="222" />
       <position x="80" y="222" />
       <position x="80" y="238" />
       <position x="54" y="238" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
    <variable formalParameter="IN_bLastChar">
     <connectionPointIn>
      <relPosition x="0" y="34" />
      <connection refLocalId="103">
       <position x="96" y="226" />
       <position x="94" y="226" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
    </variable>
   </inputVariables>
   <inOutVariables>
    <variable formalParameter="INOUT_udtComBuffer">
     <connectionPointIn>
      <relPosition x="0" y="38" />
      <connection refLocalId="99">
       <position x="96" y="230" />
       <position x="94" y="230" />
       <addData>
        <data name="connectionInformation" handleUnknown="preserve">
         <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
        </data>
       </addData>
      </connection>
     </connectionPointIn>
     <connectionPointOut>
      <relPosition x="23" y="38" />
     </connectionPointOut>
    </variable>
   </inOutVariables>
   <outputVariables>
    <variable formalParameter="OUT_DataValid">
     <connectionPointOut>
      <relPosition x="23" y="6" />
     </connectionPointOut>
    </variable>
   </outputVariables>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
    <data name="blockInformation" handleUnknown="preserve">
     <blockInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" canEditLabel="true" extensible="false" imageWidth="8" imageHeight="0" />
    </data>
    <data name="parameterInformations" handleUnknown="preserve">
     <parameterInformations xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <parameterInformation formalParameter="IN_xActivate" localId="213" executionOrderId="29" negatable="true" editorParameter="false" priority="1" />
      <parameterInformation formalParameter="IN_iYear" localId="214" executionOrderId="29" editorParameter="false" priority="2" />
      <parameterInformation formalParameter="IN_iMonth" localId="215" executionOrderId="29" editorParameter="false" priority="3" />
      <parameterInformation formalParameter="IN_iDay" localId="216" executionOrderId="29" editorParameter="false" priority="4" />
      <parameterInformation formalParameter="IN_iHour" localId="217" executionOrderId="29" editorParameter="false" priority="5" />
      <parameterInformation formalParameter="IN_iMinute" localId="264" executionOrderId="29" editorParameter="false" priority="6" />
      <parameterInformation formalParameter="IN_iSecond" localId="265" executionOrderId="29" editorParameter="false" priority="7" />
      <parameterInformation formalParameter="IN_bLastChar" localId="266" executionOrderId="29" negatable="true" editorParameter="false" priority="8" />
      <parameterInformation formalParameter="OUT_DataValid" localId="267" executionOrderId="29" negatable="true" editorParameter="false" priority="9" />
      <parameterInformation formalParameter="INOUT_udtComBuffer" localId="268" executionOrderId="29" editorParameter="false" priority="10" />
     </parameterInformations>
    </data>
   </addData>
  </block>
  <outVariable localId="105" height="4" width="13" executionOrderId="30">
   <position x="121" y="196" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="269" formalParameter="OUT_DataValid">
     <position x="121" y="198" />
     <position x="119" y="198" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>xReadyCom</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
  <outVariable localId="100" height="4" width="13" executionOrderId="31">
   <position x="121" y="228" />
   <connectionPointIn>
    <relPosition x="0" y="2" />
    <connection refLocalId="269" formalParameter="INOUT_udtComBuffer">
     <position x="121" y="230" />
     <position x="119" y="230" />
     <addData>
      <data name="connectionInformation" handleUnknown="preserve">
       <connectionInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useAutoConnector="false" useUserConnector="false" invisible="false" wasExplicitFeedback="false" />
      </data>
     </addData>
    </connection>
   </connectionPointIn>
   <expression>udtComBuffer</expression>
   <addData>
    <data name="objectInformation" handleUnknown="preserve">
     <objectInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" networkId="5" subNetworkId="0" />
    </data>
   </addData>
  </outVariable>
 </LD>
 <addData>
  <data name="docInformation" handleUnknown="preserve">
   <docInformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" gridActive="true" pageWidth="-1">
    <version>2.4.7.1183.0:A1.1</version>
    <multilineOptions maximumContactWidth="18" minimumContactWidth="18" maximumContactLines="7" contactEllipse="true" maximumInstanceNameWidth="32" maximumInstanceNameLines="5" instanceNameEllipse="true" maximumVariableWidth="2147483647" variableEllipse="false" />
   </docInformation>
  </data>
 </addData>
</body>